services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'  # Remplacer par la valeur appropriée
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'   # Port par défaut pour HTTP
      - '5173:5173'  # Port pour Vite si utilisé
    environment:
      WWWUSER: '1000'  # Remplacer par la valeur appropriée
      LARAVEL_SAIL: 1
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
      IGNITION_LOCAL_SITES_PATH: '/var/www/html'  # Vérifier le chemin
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'  # Remplacer par votre mot de passe
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'laravel'  # Nom de la base de données
      MYSQL_USER: 'sail'  # Utilisateur de la base de données
      MYSQL_PASSWORD: 'password'  # Remplacer par votre mot de passe
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-ppassword'  # Utiliser le même mot de passe défini ci-dessus
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'password'  # Utiliser le même mot de passe que pour le service MySQL
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
