version: '3'

services:
  # Service Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravelapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravelapp
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  # Service MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - dbdata:/var/lib/mysql

  # Service PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    tty: true
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - laravel
    ports:
      - "8080:80"

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
